<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class InventoryItemsTableSeeder extends Seeder
{
    /**
     * Auto generated seeder file.
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('inventory_items')->delete();
        
        \DB::table('inventory_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'code' => 'R9-INV-00001',
                'old_code' => NULL,
                'name' => 'Acetamide Broth',
                'img' => 'avatar.jpg',
                'reorder' => 500,
                'laboratory_id' => 2,
                'unit_id' => 39,
                'category_id' => 33,
                'agency_id' => 14,
                'is_active' => 1,
                'created_at' => '2025-03-17 05:13:52',
                'updated_at' => '2025-03-17 05:13:52',
            ),
            1 => 
            array (
                'id' => 2,
                'code' => 'R9-INV-00002',
                'old_code' => NULL,
            'name' => 'Acetamide Broth (Twin Pack)',
                'img' => 'avatar.jpg',
                'reorder' => 500,
                'laboratory_id' => 2,
                'unit_id' => 39,
                'category_id' => 33,
                'agency_id' => 14,
                'is_active' => 1,
                'created_at' => '2025-04-21 04:42:31',
                'updated_at' => '2025-04-21 04:42:31',
            ),
            2 => 
            array (
                'id' => 3,
                'code' => 'R9-INV-00003',
                'old_code' => NULL,
                'name' => 'Asparagine Broth',
                'img' => 'avatar.jpg',
                'reorder' => 500,
                'laboratory_id' => 2,
                'unit_id' => 39,
                'category_id' => 33,
                'agency_id' => 14,
                'is_active' => 1,
                'created_at' => '2025-04-21 04:50:46',
                'updated_at' => '2025-04-21 04:50:46',
            ),
            3 => 
            array (
                'id' => 5,
                'code' => 'R9-INV-00004',
                'old_code' => NULL,
                'name' => 'Bacteriological Agar',
                'img' => 'avatar.jpg',
                'reorder' => 500,
                'laboratory_id' => 2,
                'unit_id' => 39,
                'category_id' => 33,
                'agency_id' => 14,
                'is_active' => 1,
                'created_at' => '2025-04-21 04:59:02',
                'updated_at' => '2025-04-21 04:59:02',
            ),
            4 => 
            array (
                'id' => 6,
                'code' => 'R9-INV-00005',
                'old_code' => NULL,
                'name' => 'Baird Parker Agar',
                'img' => 'avatar.jpg',
                'reorder' => 500,
                'laboratory_id' => 2,
                'unit_id' => 39,
                'category_id' => 33,
                'agency_id' => 14,
                'is_active' => 1,
                'created_at' => '2025-04-21 05:02:29',
                'updated_at' => '2025-04-21 05:02:29',
            ),
            5 => 
            array (
                'id' => 7,
                'code' => 'R9-INV-00006',
                'old_code' => NULL,
                'name' => 'Beef Extract',
                'img' => 'avatar.jpg',
                'reorder' => 500,
                'laboratory_id' => 2,
                'unit_id' => 39,
                'category_id' => 33,
                'agency_id' => 14,
                'is_active' => 1,
                'created_at' => '2025-04-21 05:10:40',
                'updated_at' => '2025-04-21 05:10:40',
            ),
            6 => 
            array (
                'id' => 8,
                'code' => 'R9-INV-00007',
                'old_code' => NULL,
                'name' => 'Bile Esculin Agar',
                'img' => 'avatar.jpg',
                'reorder' => 500,
                'laboratory_id' => 2,
                'unit_id' => 39,
                'category_id' => 33,
                'agency_id' => 14,
                'is_active' => 1,
                'created_at' => '2025-04-21 05:17:21',
                'updated_at' => '2025-04-21 05:17:21',
            ),
            7 => 
            array (
                'id' => 9,
                'code' => 'R9-INV-00008',
                'old_code' => NULL,
                'name' => 'Brain Heart Infusion Agar',
                'img' => 'avatar.jpg',
                'reorder' => 500,
                'laboratory_id' => 2,
                'unit_id' => 39,
                'category_id' => 33,
                'agency_id' => 14,
                'is_active' => 1,
                'created_at' => '2025-04-21 05:20:19',
                'updated_at' => '2025-04-21 05:20:19',
            ),
            8 => 
            array (
                'id' => 10,
                'code' => 'R9-INV-00009',
                'old_code' => NULL,
                'name' => 'Brain Heart Infusion Broth',
                'img' => 'avatar.jpg',
                'reorder' => 500,
                'laboratory_id' => 2,
                'unit_id' => 39,
                'category_id' => 33,
                'agency_id' => 14,
                'is_active' => 1,
                'created_at' => '2025-04-21 05:23:38',
                'updated_at' => '2025-04-21 05:23:38',
            ),
            9 => 
            array (
                'id' => 11,
                'code' => 'R9-INV-00010',
                'old_code' => NULL,
                'name' => 'Brilliant Green Bile Broth',
                'img' => 'avatar.jpg',
                'reorder' => 500,
                'laboratory_id' => 2,
                'unit_id' => 39,
                'category_id' => 33,
                'agency_id' => 14,
                'is_active' => 1,
                'created_at' => '2025-04-21 05:31:40',
                'updated_at' => '2025-04-21 05:31:40',
            ),
            10 => 
            array (
                'id' => 12,
                'code' => 'R9-INV-00011',
                'old_code' => NULL,
                'name' => 'Cooked Meat Medium',
                'img' => 'avatar.jpg',
                'reorder' => 500,
                'laboratory_id' => 2,
                'unit_id' => 39,
                'category_id' => 33,
                'agency_id' => 14,
                'is_active' => 1,
                'created_at' => '2025-04-21 05:36:48',
                'updated_at' => '2025-04-21 05:36:48',
            ),
            11 => 
            array (
                'id' => 13,
                'code' => 'R9-INV-00012',
                'old_code' => NULL,
                'name' => 'Dichloran-Rose Bengal Chloramphenicol Agar',
                'img' => 'avatar.jpg',
                'reorder' => 500,
                'laboratory_id' => 2,
                'unit_id' => 39,
                'category_id' => 33,
                'agency_id' => 14,
                'is_active' => 1,
                'created_at' => '2025-04-21 05:51:50',
                'updated_at' => '2025-04-21 05:51:50',
            ),
            12 => 
            array (
                'id' => 14,
                'code' => 'R9-INV-00013',
                'old_code' => NULL,
            'name' => 'Levine Agar (EMB)',
                'img' => 'avatar.jpg',
                'reorder' => 500,
                'laboratory_id' => 2,
                'unit_id' => 39,
                'category_id' => 33,
                'agency_id' => 14,
                'is_active' => 1,
                'created_at' => '2025-04-21 05:56:33',
                'updated_at' => '2025-04-21 05:56:33',
            ),
            13 => 
            array (
                'id' => 15,
                'code' => 'R9-INV-00014',
                'old_code' => NULL,
                'name' => 'Malt Extract Broth',
                'img' => 'avatar.jpg',
                'reorder' => 500,
                'laboratory_id' => 2,
                'unit_id' => 39,
                'category_id' => 33,
                'agency_id' => 14,
                'is_active' => 1,
                'created_at' => '2025-04-21 05:59:13',
                'updated_at' => '2025-04-21 05:59:13',
            ),
            14 => 
            array (
                'id' => 16,
                'code' => 'R9-INV-00015',
                'old_code' => NULL,
            'name' => 'Lauryl Sulfate Broth (Lauryl Tryptose Broth)',
                'img' => 'avatar.jpg',
                'reorder' => 500,
                'laboratory_id' => 2,
                'unit_id' => 39,
                'category_id' => 33,
                'agency_id' => 14,
                'is_active' => 1,
                'created_at' => '2025-04-21 05:59:49',
                'updated_at' => '2025-04-21 05:59:49',
            ),
            15 => 
            array (
                'id' => 17,
                'code' => 'R9-INV-00016',
                'old_code' => NULL,
                'name' => 'MR-VP Medium',
                'img' => 'avatar.jpg',
                'reorder' => 500,
                'laboratory_id' => 2,
                'unit_id' => 39,
                'category_id' => 33,
                'agency_id' => 14,
                'is_active' => 1,
                'created_at' => '2025-04-21 06:01:53',
                'updated_at' => '2025-04-21 06:01:53',
            ),
            16 => 
            array (
                'id' => 18,
                'code' => 'R9-INV-00017',
                'old_code' => NULL,
                'name' => 'Nutrient Agar',
                'img' => 'avatar.jpg',
                'reorder' => 500,
                'laboratory_id' => 2,
                'unit_id' => 39,
                'category_id' => 33,
                'agency_id' => 14,
                'is_active' => 1,
                'created_at' => '2025-04-21 06:06:46',
                'updated_at' => '2025-04-21 06:06:46',
            ),
            17 => 
            array (
                'id' => 19,
                'code' => 'R9-INV-00018',
                'old_code' => NULL,
                'name' => 'Plate Count Agar',
                'img' => 'avatar.jpg',
                'reorder' => 500,
                'laboratory_id' => 2,
                'unit_id' => 39,
                'category_id' => 33,
                'agency_id' => 14,
                'is_active' => 1,
                'created_at' => '2025-04-21 06:07:12',
                'updated_at' => '2025-04-21 06:07:12',
            ),
            18 => 
            array (
                'id' => 20,
                'code' => 'R9-INV-00019',
                'old_code' => NULL,
            'name' => 'Trypticasein Soy Agar (TSA)',
                'img' => 'avatar.jpg',
                'reorder' => 500,
                'laboratory_id' => 2,
                'unit_id' => 39,
                'category_id' => 33,
                'agency_id' => 14,
                'is_active' => 1,
                'created_at' => '2025-04-21 06:08:04',
                'updated_at' => '2025-04-21 06:08:04',
            ),
            19 => 
            array (
                'id' => 21,
                'code' => 'R9-INV-00020',
                'old_code' => NULL,
                'name' => 'Mueller-Hinton Agar',
                'img' => 'avatar.jpg',
                'reorder' => 500,
                'laboratory_id' => 2,
                'unit_id' => 39,
                'category_id' => 33,
                'agency_id' => 14,
                'is_active' => 1,
                'created_at' => '2025-04-21 06:14:54',
                'updated_at' => '2025-04-21 06:14:54',
            ),
            20 => 
            array (
                'id' => 22,
                'code' => 'R9-INV-00021',
                'old_code' => NULL,
                'name' => 'Peptone',
                'img' => 'avatar.jpg',
                'reorder' => 500,
                'laboratory_id' => 2,
                'unit_id' => 39,
                'category_id' => 33,
                'agency_id' => 14,
                'is_active' => 1,
                'created_at' => '2025-04-21 06:15:16',
                'updated_at' => '2025-04-21 06:15:16',
            ),
        ));

        
    }
}