<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ListIndustriesTableSeeder extends Seeder
{
    /**
     * Auto generated seeder file.
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('list_industries')->delete();
        
        \DB::table('list_industries')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Agriculture, Forestry and Fishing',
                'industry_id' => NULL,
                'industry_type' => NULL,
                'is_main' => '1',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Mining and Quarrying',
                'industry_id' => NULL,
                'industry_type' => NULL,
                'is_main' => '1',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Manufacturing',
                'industry_id' => NULL,
                'industry_type' => NULL,
                'is_main' => '1',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Electricity, Gas, Steam and Air Conditioning Supply',
                'industry_id' => NULL,
                'industry_type' => NULL,
                'is_main' => '1',
                'is_alone' => '1',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Water Supply, Sewerage, Waste Management and Remediation Activities',
                'industry_id' => NULL,
                'industry_type' => NULL,
                'is_main' => '1',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Construction',
                'industry_id' => NULL,
                'industry_type' => NULL,
                'is_main' => '1',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Wholesale and Retail Trade; Repair of Motor Vehicles and Motorcycles',
                'industry_id' => NULL,
                'industry_type' => NULL,
                'is_main' => '1',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Transportation and Storage',
                'industry_id' => NULL,
                'industry_type' => NULL,
                'is_main' => '1',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Accommodation and Food Service Activities',
                'industry_id' => NULL,
                'industry_type' => NULL,
                'is_main' => '1',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Information and Communication',
                'industry_id' => NULL,
                'industry_type' => NULL,
                'is_main' => '1',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Financial and Insurance Activities',
                'industry_id' => NULL,
                'industry_type' => NULL,
                'is_main' => '1',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Real Estate Activities',
                'industry_id' => NULL,
                'industry_type' => NULL,
                'is_main' => '1',
                'is_alone' => '1',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Professional, Scientific and Technical Activities',
                'industry_id' => NULL,
                'industry_type' => NULL,
                'is_main' => '1',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Administrative and Support Service Activities',
                'industry_id' => NULL,
                'industry_type' => NULL,
                'is_main' => '1',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Public Administration and Defense; Compulsory Social Security',
                'industry_id' => NULL,
                'industry_type' => NULL,
                'is_main' => '1',
                'is_alone' => '1',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Education',
                'industry_id' => NULL,
                'industry_type' => NULL,
                'is_main' => '1',
                'is_alone' => '1',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Human Health and Social Work Activities',
                'industry_id' => NULL,
                'industry_type' => NULL,
                'is_main' => '1',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Arts, Entertainment and Recreation',
                'industry_id' => NULL,
                'industry_type' => NULL,
                'is_main' => '1',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'Other Service Activities',
                'industry_id' => NULL,
                'industry_type' => NULL,
                'is_main' => '1',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Activities of Households as Employers',
                'industry_id' => NULL,
                'industry_type' => NULL,
                'is_main' => '1',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'Activities of Extra-Territorial Organizations and Bodies',
                'industry_id' => NULL,
                'industry_type' => NULL,
                'is_main' => '1',
                'is_alone' => '1',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'Government',
                'industry_id' => NULL,
                'industry_type' => NULL,
                'is_main' => '1',
                'is_alone' => '1',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'Crop and Animal Production, Hunting and Related Service Activities',
                'industry_id' => 1,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'Forestry and Logging',
                'industry_id' => 1,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'Fishing and Aquaculture',
                'industry_id' => 1,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'Mining of Coal and Lignite',
                'industry_id' => 2,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'Extraction of Crude Petroleum and Natural Gas',
                'industry_id' => 2,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'Mining of Metal Ores',
                'industry_id' => 2,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'Other Mining and Quarrying',
                'industry_id' => 2,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'Mining Support Service Activities',
                'industry_id' => 2,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'Manufacture of Food Products',
                'industry_id' => 3,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'Manufacture of Beverages',
                'industry_id' => 3,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'Manufacture of Tobacco Products',
                'industry_id' => 3,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'Manufacture of Textiles',
                'industry_id' => 3,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'Manufacture of Wearing Apparel',
                'industry_id' => 3,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'Manufacture of Leather and Related Products',
                'industry_id' => 3,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'Manufacture Of Wood And Of Products of Wood and Cork, Except Furniture',
                'industry_id' => 3,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'Manufacture of Articles of Bamboo, Cane, Rattan and The Like',
                'industry_id' => 3,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'Manufacture of Articles of Straw and Plaiting Materials',
                'industry_id' => 3,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'Printing and Reproduction of Recorded Media',
                'industry_id' => 3,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'Manufacture of Coke and Refined Petroleum Products',
                'industry_id' => 3,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            41 => 
            array (
                'id' => 42,
                'name' => 'Manufacture of Chemicals and Chemical Products',
                'industry_id' => 3,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            42 => 
            array (
                'id' => 43,
                'name' => 'Manufacture of Basic Pharmaceutical Products and Pharmaceutical Preparations',
                'industry_id' => 3,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            43 => 
            array (
                'id' => 44,
                'name' => 'Manufacture of Rubber and Plastic Products',
                'industry_id' => 3,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            44 => 
            array (
                'id' => 45,
                'name' => 'Manufacture of Other Non-Metallic Mineral Products',
                'industry_id' => 3,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            45 => 
            array (
                'id' => 46,
                'name' => 'Manufacture of Basic Metals',
                'industry_id' => 3,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            46 => 
            array (
                'id' => 47,
                'name' => 'Manufacture of Fabricated Metal Products, Except Machinery and Equipment',
                'industry_id' => 3,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            47 => 
            array (
                'id' => 48,
                'name' => 'Manufacture of Computer, Electronic and Optical Products',
                'industry_id' => 3,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            48 => 
            array (
                'id' => 49,
                'name' => 'Manufacture of Electrical Equipment',
                'industry_id' => 3,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            49 => 
            array (
                'id' => 50,
                'name' => 'Manufacture of Machinery and Equipment, NEC',
                'industry_id' => 3,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            50 => 
            array (
                'id' => 51,
                'name' => 'Manufacture of Motor Vehicles, Trailers and Semi-Trailers',
                'industry_id' => 3,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            51 => 
            array (
                'id' => 52,
                'name' => 'Manufacture of Other Transport Equipment',
                'industry_id' => 3,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            52 => 
            array (
                'id' => 53,
                'name' => 'Manufacture Of Furniture',
                'industry_id' => 3,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            53 => 
            array (
                'id' => 54,
                'name' => 'Other Manufacturing',
                'industry_id' => 3,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            54 => 
            array (
                'id' => 55,
                'name' => 'Repair and Installation of Machinery and Equipment',
                'industry_id' => 3,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            55 => 
            array (
                'id' => 56,
                'name' => 'Water Collection, Treatment and Supply',
                'industry_id' => 5,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            56 => 
            array (
                'id' => 57,
                'name' => 'Sewerage',
                'industry_id' => 5,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            57 => 
            array (
                'id' => 58,
                'name' => 'Waste Collection, Treatment and Disposal Activities; Materials Recovery',
                'industry_id' => 5,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            58 => 
            array (
                'id' => 59,
                'name' => 'Remediation Activities and Other Waste Management Services',
                'industry_id' => 5,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            59 => 
            array (
                'id' => 60,
                'name' => 'Construction of Buildings',
                'industry_id' => 6,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            60 => 
            array (
                'id' => 61,
                'name' => 'Civil Engineering',
                'industry_id' => 6,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            61 => 
            array (
                'id' => 62,
                'name' => 'Specialized Construction Activities',
                'industry_id' => 6,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            62 => 
            array (
                'id' => 63,
                'name' => 'Wholesale and Retail Trade and Repair of Motor Vehicles and Motorcycles',
                'industry_id' => 7,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            63 => 
            array (
                'id' => 64,
                'name' => 'Wholesale Trade, Except of Motor Vehicles and Motorcycles',
                'industry_id' => 7,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            64 => 
            array (
                'id' => 65,
                'name' => 'Retail Trade, Except of Motor Vehicles and Motorcycles',
                'industry_id' => 7,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            65 => 
            array (
                'id' => 66,
                'name' => 'Land Transport and Transport via Pipelines',
                'industry_id' => 8,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            66 => 
            array (
                'id' => 67,
                'name' => 'Water Transport',
                'industry_id' => 8,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            67 => 
            array (
                'id' => 68,
                'name' => 'Air Transport',
                'industry_id' => 8,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            68 => 
            array (
                'id' => 69,
                'name' => 'Warehousing and Support Activities for Transportation',
                'industry_id' => 8,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            69 => 
            array (
                'id' => 70,
                'name' => 'Postal and Courier Activities',
                'industry_id' => 8,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            70 => 
            array (
                'id' => 71,
                'name' => 'Accommodation',
                'industry_id' => 9,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            71 => 
            array (
                'id' => 72,
                'name' => 'Food and Beverage Service Activities',
                'industry_id' => 9,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            72 => 
            array (
                'id' => 73,
                'name' => 'Publishing Activities',
                'industry_id' => 10,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            73 => 
            array (
                'id' => 74,
                'name' => 'Motion Picture, Video and Television Programme Production, Sound Recording and Music Publishing Activities',
                'industry_id' => 10,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            74 => 
            array (
                'id' => 75,
                'name' => 'Programming and Broadcasting Activities',
                'industry_id' => 10,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            75 => 
            array (
                'id' => 76,
                'name' => 'Telecommunications',
                'industry_id' => 10,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            76 => 
            array (
                'id' => 77,
                'name' => 'Computer Programming, Consultancy and Related Activities',
                'industry_id' => 10,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            77 => 
            array (
                'id' => 78,
                'name' => 'Information Service Activities',
                'industry_id' => 10,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            78 => 
            array (
                'id' => 79,
                'name' => 'Financial Service Activities, Except Insurance and Pension Funding',
                'industry_id' => 11,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            79 => 
            array (
                'id' => 80,
                'name' => 'Insurance, Reinsurance and Pension Funding, Except Compulsory Social Security',
                'industry_id' => 11,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            80 => 
            array (
                'id' => 81,
                'name' => 'Activities Auxiliary to Financial Service and Insurance Activities',
                'industry_id' => 11,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            81 => 
            array (
                'id' => 82,
                'name' => 'Legal and Accounting Activities',
                'industry_id' => 13,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            82 => 
            array (
                'id' => 83,
                'name' => 'Activities of Head Offices; Management Consultancy Activities',
                'industry_id' => 13,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            83 => 
            array (
                'id' => 84,
                'name' => 'Architectural and Engineering Activities; Technical Testing and Analysis',
                'industry_id' => 13,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            84 => 
            array (
                'id' => 85,
                'name' => 'Scientific Research and Development',
                'industry_id' => 13,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            85 => 
            array (
                'id' => 86,
                'name' => 'Advertising and Market Research',
                'industry_id' => 13,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            86 => 
            array (
                'id' => 87,
                'name' => 'Other Professional, Scientific and Technical Activities',
                'industry_id' => 13,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            87 => 
            array (
                'id' => 88,
                'name' => 'Veterinary Activities',
                'industry_id' => 13,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            88 => 
            array (
                'id' => 89,
                'name' => 'Rental and Leasing Activities',
                'industry_id' => 14,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            89 => 
            array (
                'id' => 90,
                'name' => 'Employment Activities',
                'industry_id' => 14,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            90 => 
            array (
                'id' => 91,
                'name' => 'Travel Agency, Tour Operator, Reservation Service and Related Activities',
                'industry_id' => 14,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            91 => 
            array (
                'id' => 92,
                'name' => 'Security and Investigation Activities',
                'industry_id' => 14,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            92 => 
            array (
                'id' => 93,
                'name' => 'Services to Buildings and Landscape Activities',
                'industry_id' => 14,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            93 => 
            array (
                'id' => 94,
                'name' => 'Office Administrative, Office Support and Other Business Support Activities',
                'industry_id' => 14,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            94 => 
            array (
                'id' => 95,
                'name' => 'Human Health Activities',
                'industry_id' => 17,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            95 => 
            array (
                'id' => 96,
                'name' => 'Residential Care Activities',
                'industry_id' => 17,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            96 => 
            array (
                'id' => 97,
                'name' => 'Social Work Activities Without Accommodation',
                'industry_id' => 17,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            97 => 
            array (
                'id' => 98,
                'name' => 'Creative, Arts and Entertainment Activities',
                'industry_id' => 18,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            98 => 
            array (
                'id' => 99,
                'name' => 'Libraries, Archives, Museums and Other Cultural Activities',
                'industry_id' => 18,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            99 => 
            array (
                'id' => 100,
                'name' => 'Gambling and Betting Activities',
                'industry_id' => 18,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            100 => 
            array (
                'id' => 101,
                'name' => 'Sports Activities and Amusement and Recreation Activities',
                'industry_id' => 18,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            101 => 
            array (
                'id' => 102,
                'name' => 'Activities of Membership Organizations',
                'industry_id' => 19,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            102 => 
            array (
                'id' => 103,
                'name' => 'Repair of Computers and Personal and Household Goods',
                'industry_id' => 19,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            103 => 
            array (
                'id' => 104,
                'name' => 'Other Personal Service Activities',
                'industry_id' => 19,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            104 => 
            array (
                'id' => 105,
                'name' => 'Activities of Households as Employers of Domestic Personnel',
                'industry_id' => 20,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            105 => 
            array (
                'id' => 106,
                'name' => 'Undifferentiated Goods-and Services-Producing Activities of Private Households for Own Use',
                'industry_id' => 20,
                'industry_type' => 'App\\Models\\ListIndustry',
                'is_main' => '0',
                'is_alone' => '0',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
            106 => 
            array (
                'id' => 107,
                'name' => 'Individual',
                'industry_id' => NULL,
                'industry_type' => NULL,
                'is_main' => '1',
                'is_alone' => '1',
                'is_active' => 1,
                'created_at' => '2024-07-30 19:23:25',
                'updated_at' => '2024-07-30 19:23:25',
            ),
        ));

        
    }
}