<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    /**
     * Auto generated seeder file.
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->truncate();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'username' => 'administrator',
                'email' => 'kradjumli@gmail.com',
                'password' => '$2y$12$JaSRqO0h7h7uppujY2K6T.CJ0N6ndGLi8/Z53Raz.hFMs6O5vUarG',
                'role' => 'Administrator',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => '2024-05-15 16:46:33',
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-05-14 22:10:35',
                'updated_at' => '2025-05-14 22:10:35',
            ),
            1 => 
            array (
                'id' => 2,
                'username' => 'mbg',
                'email' => 'lina.gelonga@ro6.dost.gov.ph',
                'password' => '$2y$12$AW3lff46ATLoHyCVn3Ugkeoi9Cu0IXTmxSApwq.BIwv2/8HpXXmPu',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => '2024-05-15 16:46:33',
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-05-15 16:24:24',
                'updated_at' => '2025-05-15 16:24:31',
            ),
            2 => 
            array (
                'id' => 3,
                'username' => 'sec',
                'email' => 'stonehilljec.dost6@gmail.com',
                'password' => '$2y$12$xm5oOjffkKwBHAk2tc0Ieu2SPTrcoENE3D5UgDt0ZO51OxCfE6xB6',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => 'AlDlhYiocLPzLg53WlLBjlyEiTqAZXdwxdoScu08YC9Q7uRC9YpeHgQz4Zwa',
                'email_verified_at' => '2024-05-15 16:46:33',
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-05-15 16:25:15',
                'updated_at' => '2025-05-15 16:37:46',
            ),
            3 => 
            array (
                'id' => 4,
                'username' => 'fsb',
                'email' => 'fjie1021@gmail.com',
                'password' => '$2y$12$d3D9Fd0AgHXVUIKL6z/YneBi0UdGkn7wmhdr5bh2QQfz5u22318vG',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => '2024-05-15 16:46:33',
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-05-15 16:25:55',
                'updated_at' => '2025-05-15 16:37:50',
            ),
            4 => 
            array (
                'id' => 5,
                'username' => 'mvr',
                'email' => 'mark.rosales@ro6.dost.gov.ph',
                'password' => '$2y$12$PELO3l/F.64VnfWIclGKh.dDLp4AtP59M22HG1cyV0JLRc4iASDMm',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => '9C5Z5WDnMlBCedUGjN4XD2Ys8VGyZmWXasDCEPyQInSCSRkg1g7tsD7Xt2JQ',
                'email_verified_at' => '2024-05-15 16:46:33',
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-05-15 16:26:31',
                'updated_at' => '2025-05-15 16:37:52',
            ),
            5 => 
            array (
                'id' => 6,
                'username' => 'kaa',
                'email' => 'kirkaguirre75@gmail.com',
                'password' => '$2y$12$fk8zKehBs8LTsqA79LYTvOqVH2uJXw9wLH0lWHOofoaC3P7rmvREa',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => '2024-05-15 16:46:33',
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-05-15 16:27:50',
                'updated_at' => '2025-05-15 16:37:55',
            ),
            6 => 
            array (
                'id' => 7,
                'username' => 'jdn',
                'email' => 'navales.johnlorenzdurable@gmail.com',
                'password' => '$2y$12$2XERFxUhA6gTxr3j7vbpneB5Ox/X4EhNLkYJAuEZ0pHR9uepfOFkO',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => 'DpgLBMQUXVBhYpsknIiPS82XlWUwajolH52Chsfk46ON3gY78JZLC6FAKZlu',
                'email_verified_at' => '2024-05-15 16:46:33',
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-05-15 16:28:24',
                'updated_at' => '2025-05-15 16:37:58',
            ),
            7 => 
            array (
                'id' => 8,
                'username' => 'jpu',
                'email' => 'jessreyumadhay@gmail.com',
                'password' => '$2y$12$5Alo4DHYhuP2tqIpDolgjOXEYDV48QIzdgRoHPJUV5mtxOJk3oVJq',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => 'Jc4e1IHWD4I2yazu566twwLEIxGVbRKLPDZGxV7ZBqWTE7d3CwCllal0WUp6',
                'email_verified_at' => '2024-05-15 16:46:33',
                'password_changed_at' => '2025-05-22 15:52:37',
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-05-15 16:28:57',
                'updated_at' => '2025-05-22 15:52:37',
            ),
            8 => 
            array (
                'id' => 9,
                'username' => 'act',
                'email' => 'ticararthur26@gmail.com',
                'password' => '$2y$12$KVrftKXhlZoMltvoXdb44udAxuHKnmGCHX0kO5MUAQwtSrvFn2Nty',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => '2024-05-15 16:46:33',
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-05-15 16:30:06',
                'updated_at' => '2025-05-15 16:38:03',
            ),
            9 => 
            array (
                'id' => 10,
                'username' => 'jba',
                'email' => 'jullieanne.amancio@ro6.dost.gov.ph',
                'password' => '$2y$12$KNPSKSs1gh.iQn4CUujjPOksuoY4F9GMsYXEgQspyeJzuiPfFS57G',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => '2024-05-15 16:46:33',
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-05-15 16:31:05',
                'updated_at' => '2025-05-15 16:38:07',
            ),
            10 => 
            array (
                'id' => 11,
                'username' => 'mcc',
                'email' => 'mwpcaelian@gmail.com',
                'password' => '$2y$12$gzOeQDr5nvuZHuM2LlLS/uUN7f6IXTGmRR.Dbe/c4v6Y4JTwFFy4y',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => '2024-05-15 16:46:33',
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-05-15 16:31:38',
                'updated_at' => '2025-05-15 16:38:09',
            ),
            11 => 
            array (
                'id' => 12,
                'username' => 'kpf',
                'email' => 'kspfulgencio@gmail.com',
                'password' => '$2y$12$ObgYMggmW.CvellHrrmA3eTFeT7K8Yji5N75uf6vcgs1NagCLJRPW',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => '2024-05-15 16:46:33',
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-05-15 16:32:13',
                'updated_at' => '2025-05-15 16:39:02',
            ),
            12 => 
            array (
                'id' => 13,
                'username' => 'rbv',
                'email' => 'rosenhelvalente@gmail.com',
                'password' => '$2y$12$jD20LvJFXuzlVs9yLO/5buXdZizv1fpLZP43r.1djTmD/N6iSMZB6',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => '2024-05-15 16:46:33',
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-05-15 16:33:02',
                'updated_at' => '2025-05-15 16:39:04',
            ),
            13 => 
            array (
                'id' => 14,
                'username' => 'rgs',
                'email' => 'rsgsesbreno@ro6.dost.gov.ph',
                'password' => '$2y$12$B/VD3dWm2JuVuorSObgtweBsJApWDxsqrLN.tmHFZ9agfrk3pWIsK',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => '2024-05-15 16:46:33',
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-05-15 16:33:44',
                'updated_at' => '2025-05-15 16:39:06',
            ),
            14 => 
            array (
                'id' => 15,
                'username' => 'fal',
                'email' => 'xamlayson@gmail.com',
                'password' => '$2y$12$j3T6066wAa7iHWvZWTZm4eUuv.fm8bx6xC6.xJlqZOXQBO9NeK.lm',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => '2024-05-15 16:46:33',
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-05-15 16:34:17',
                'updated_at' => '2025-05-15 16:38:13',
            ),
            15 => 
            array (
                'id' => 16,
                'username' => 'grm',
                'email' => 'gesselle.marcon@ro6.dost.gov.ph',
                'password' => '$2y$12$DDspkdloUoznB9fZMh5bW.mLDN6KQz.H0U//NGriB9zAqMWu3gQhe',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => 'FqtUmNjkIadU1C8eTxpKcuQrTrhpK0VFKPwSpApUGXcyUCI5NHBQdpGPHxX7',
                'email_verified_at' => '2024-05-15 16:46:33',
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-05-15 16:35:09',
                'updated_at' => '2025-05-15 16:39:08',
            ),
            16 => 
            array (
                'id' => 17,
                'username' => 'jvg',
                'email' => 'joeben.gubatanga@ro6.dost.gov.ph',
                'password' => '$2y$12$FnEdWNB2VMRuMwgeqJoCSeqj62f0ZasOE5SsIdPoPpoDPeYM6PzIa',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => '3kyCKcSs1WDA8nR4kB1ecDEnVQmJGl98iCE1kPxIT1I8gzIhJG9jBhxPkJ37',
                'email_verified_at' => '2024-05-15 16:46:33',
                'password_changed_at' => '2025-07-14 19:57:51',
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-05-15 16:35:42',
                'updated_at' => '2025-07-14 19:57:51',
            ),
            17 => 
            array (
                'id' => 18,
                'username' => 'kns',
                'email' => 'kristinemae.solis@ro6.dost.gov.ph',
                'password' => '$2y$12$19xbnZ3NdAvoXhGzh0W7E.zqKK45dSb4KIPiY7D6S4nIofHc//a16',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => '2024-05-15 16:46:33',
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-05-15 16:36:18',
                'updated_at' => '2025-05-15 16:39:15',
            ),
            18 => 
            array (
                'id' => 19,
                'username' => 'afa',
                'email' => 'allendaryl.asuelo@ro6.dost.gov.ph',
                'password' => '$2y$12$6rpApCyapgoBaYbz1/eXtuguF3057C6x5dlvGx5AM9HvqK5T7aNoa',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => '2024-05-15 16:46:33',
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-05-15 16:36:49',
                'updated_at' => '2025-05-15 16:39:18',
            ),
            19 => 
            array (
                'id' => 20,
                'username' => 'zag',
                'email' => 'abianzindy@gmail.com',
                'password' => '$2y$12$Z9KtwlMvkey.Nh85Fg7nh.TPQfkbk68Q9q5CbdCbKO0xerflFOyMO',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => '2024-05-15 16:46:33',
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-05-15 16:37:23',
                'updated_at' => '2025-05-15 16:39:20',
            ),
            20 => 
            array (
                'id' => 21,
                'username' => 'mas',
                'email' => 'aliciasoledad.salazar@ro6.dost.gov.ph',
                'password' => '$2y$12$eSDHqVTaikY.8Da4..PDV.MuSrtYiZmL4vn4U5vynJYIL4qfoclqe',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => '2024-05-15 16:46:33',
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-05-16 23:07:36',
                'updated_at' => '2025-05-19 17:41:28',
            ),
            21 => 
            array (
                'id' => 22,
                'username' => 'rgl',
                'email' => 'rubyann.llaneta@ro6.dost.gov.ph',
                'password' => '$2y$12$3XRwGSIkRrR796iaXh88DOlQcOracw.MnS60DLkoctkKYKdZUfYbC',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => '2024-05-15 16:46:33',
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-05-16 23:43:05',
                'updated_at' => '2025-05-19 17:41:50',
            ),
            22 => 
            array (
                'id' => 23,
                'username' => 'aud',
                'email' => 'antonette.donato@ro6.dost.gov.ph',
                'password' => '$2y$12$nUCFq4X9nGIV/KqoSOGcn.QIb7qAF/3NQnfaIGQmPqpu7tS.smWpW',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => '2024-05-15 16:46:33',
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-05-19 17:44:48',
                'updated_at' => '2025-05-19 17:50:35',
            ),
            23 => 
            array (
                'id' => 24,
                'username' => 'rjd',
                'email' => 'ryanvilmor.dumpit@ro6.dost.gov.ph',
                'password' => '$2y$12$F5VxZ14b3W6mHQWZ/zkQFeIcddwaeFWUiIfpmNgoYeRSeG.CY.7pi',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => 'eyJpdiI6Ilgxc0laU09PUUY1ckpVeXpkM0IrYUE9PSIsInZhbHVlIjoiV2NxT0g3Zzh0SXNWUzdPRHdpUTNreXI5aGtWcUtyLy9xY0hXMHFHbm5DOVRvdGh1eExmengyQ0Z0K0xEWHpIOWU0alpvTWFMbkVNMmczajU0bW80YWx0cUl6MFgrYS9TRDNLUFZ2Kzk5UFMxUHQwN1l0cUVMTHErREZCeXhwWWpGeE9RUHJ5dFdaakFrR1Q4elN6ZmhZMDYxYjA0Z0hSU2RmU0lyRkQzKzBDY01RNG53ZmsvS1hRZ3hKNUZXb0tCSlpZeWpaaHlGT1ZraGZXQWVDaTJYS1NsQWdBZGVTOXVweTQ4YnBwdllNUndtMFByZTJUQy9KQUJFcmRLMGlKSmx6SngrYkRBZ2lmVzV6T3RYWFRrb0E9PSIsIm1hYyI6IjM1MTRkNzQxYzhiMjFhOWI0M2VlZTY3NTM4MjhmZTc3OGY0NjNkYWM1MWNiNGE0NTVlNGE0YjM2MTM5YTQ5YjciLCJ0YWciOiIifQ==',
                'remember_token' => NULL,
                'email_verified_at' => '2024-05-15 16:46:33',
                'password_changed_at' => '2025-05-20 17:45:46',
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-05-19 17:45:42',
                'updated_at' => '2025-05-20 17:46:11',
            ),
            24 => 
            array (
                'id' => 25,
                'username' => 'mcp',
                'email' => 'mia.pielago@ro6.dost.gov.ph',
                'password' => '$2y$12$KSgmNzMW3mpWoUDKjz64PeAuCFpfrD5bpNcRZlGp6TpBgn9mUzwTm',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => 'xrr9v81KmCSf0jhVyZbADIBu7rGUxhgqoZK2QNfNdaNNBxfeRTTvLrSQce3x',
                'email_verified_at' => '2024-05-15 16:46:33',
                'password_changed_at' => '2025-06-04 23:11:40',
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-05-19 17:47:01',
                'updated_at' => '2025-06-04 23:11:40',
            ),
            25 => 
            array (
                'id' => 26,
                'username' => 'vmp',
                'email' => 'vernamyrtel.poncedeleon@ro6.dost.gov.ph',
                'password' => '$2y$12$YrXEOhfxiYJhVTVv5TQhZe9ulxK.fFAaL3AoDH/MJMFDDc6HAfD.m',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => '2024-05-15 16:46:33',
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-05-19 17:49:43',
                'updated_at' => '2025-05-19 17:50:42',
            ),
            26 => 
            array (
                'id' => 27,
                'username' => 'erp',
                'email' => 'eunice.panagsagan@ro6.dost.gov.ph',
                'password' => '$2y$12$DPj93s9oHIV4L6A5dk7wcupC....paewoy8QsxCA/05y.PIragm3K',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => 'pviSCYsrK80i1fvOXbBOMT3eiT2ffwbpFAmzhgUNV0cKVOCHlgRal8Kn2O0U',
                'email_verified_at' => '2024-05-15 16:46:33',
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-05-19 17:50:26',
                'updated_at' => '2025-05-19 17:50:44',
            ),
            27 => 
            array (
                'id' => 28,
                'username' => 'cqp',
                'email' => 'charlespalla@gmail.com',
                'password' => '$2y$12$OoJvWe4zULiFtprdGIV2/OTCJ2uDmxvv8zr5edoagN7GIjh0wAIXm',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => '2024-05-15 16:46:33',
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-05-19 17:53:30',
                'updated_at' => '2025-05-19 17:53:34',
            ),
            28 => 
            array (
                'id' => 29,
                'username' => 'cashier',
                'email' => 'cashier@ro6.dost.gov.ph',
                'password' => '$2y$12$lgNZ3tX3PcVQsMR8a6DQT.mBvV6kqnCq46erypABac.r42hEKT3.S',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => '9Dx4YjmomS9t2M8bh5hVnfo0wlb3veerz2PHBKj3k3QLY8arVkVhd2PGWW97',
                'email_verified_at' => '2024-05-15 16:46:33',
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-05-19 23:55:15',
                'updated_at' => '2025-05-19 23:55:19',
            ),
            29 => 
            array (
                'id' => 30,
                'username' => 'GLL',
                'email' => 'accounting@ro6.dost.gov.ph',
                'password' => '$2y$12$KzCKyrR3Q69O6kxGqr/.COgi5MblHSRuB48SbybCTt1E/xgwjC0E2',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => 'mHHFYUCM0SBFFX0pIqL1ZfwFScki7tK4GXUAXbxlyye5ArawQQZdZwmaScKW',
                'email_verified_at' => '2024-05-15 16:46:33',
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-05-20 00:05:17',
                'updated_at' => '2025-05-20 00:05:24',
            ),
        ));

        
    }
}