<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    /**
     * Auto generated seeder file.
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'username' => 'administrator',
                'email' => 'kradjumli@gmail.com',
                'password' => '$2y$12$LN8VcjcG44Sg6ix5nQp6k.qjHLuGc6gXBDPIlz6wDekCXS90jqltm',
                'role' => 'Administrator',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => '2024-05-15 16:46:33',
                'password_changed_at' => '2024-09-09 16:57:39',
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2024-07-30 16:19:03',
                'updated_at' => '2024-09-09 16:57:39',
            ),
            1 => 
            array (
                'id' => 2,
                'username' => 'jpf',
                'email' => 'joefryfernando@gmail.com',
                'password' => '$2y$12$hGBPer/NIcGYsyxriG8cIOUgmMpzg/RmyTxyq6cqzGlDzPoIdOIcu',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => 'HMBSnloLQxGPftGAuc6AYYuSzhm6vtUHQqMk3pke1yfC3RgROwZ63pS6iCMl',
                'email_verified_at' => '2024-05-15 16:46:33',
                'password_changed_at' => '2024-09-09 17:22:14',
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2024-07-30 19:04:54',
                'updated_at' => '2024-09-09 17:22:14',
            ),
            2 => 
            array (
                'id' => 3,
                'username' => 'jjb',
                'email' => 'jali_badiola2005@yahoo.com',
                'password' => '$2y$12$Dv1kH.t1XFVdu1u0ZDcflObQh3JTCUktPTfM16ICkcTkOlaWUQ1Cu',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => 'eH8vSgqumHuY3SABA9zPZ1qJyMzKVox9OWc1uqUTQSY6FqOTYZWEOhyujWgT',
                'email_verified_at' => '2024-05-15 16:46:33',
                'password_changed_at' => '2024-09-09 18:11:06',
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2024-08-03 22:46:56',
                'updated_at' => '2024-09-09 18:11:06',
            ),
            3 => 
            array (
                'id' => 4,
                'username' => 'ita',
                'email' => 'ingridtac.dostro09@yahoo.com',
                'password' => '$2y$12$OYBjfzgMtaSa1TewfK7lJOkT2OJ3jPpoPvZcdbHr5Qa2.JpZs6PzC',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => '89ovGBwwOnYBekF5c0Lwtxe69En4UeX913IFjeb3A56ZcJfRHVB6xu7kMQoz',
                'email_verified_at' => '2024-05-15 16:46:33',
                'password_changed_at' => '2024-09-09 18:10:12',
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2024-08-03 22:47:33',
                'updated_at' => '2024-09-09 18:10:12',
            ),
            4 => 
            array (
                'id' => 5,
                'username' => 'jtf',
                'email' => 'schezzojuly@gmail.com',
                'password' => '$2y$12$llv2A5LWgk5r6gxXjW.zEurDxQJHjWs9v6CsA9RTn960dXNm7Kjwy',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => '176v95TeEC6wa2rHDKiUezVfHT1wlw0iV29lEYPqhQfdZti5Sud6x5j6BNet',
                'email_verified_at' => '2024-05-15 16:46:33',
                'password_changed_at' => '2024-09-11 16:29:41',
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2024-09-02 18:54:01',
                'updated_at' => '2024-09-26 17:14:56',
            ),
            5 => 
            array (
                'id' => 6,
                'username' => 'slb',
                'email' => 'sonora.bunag@ro9.dost.gov.ph',
                'password' => '$2y$12$bIvYodrcjyxgpjHT0RIAZux/UpZJxUjxk5mQB9mJ8vnFv8iHSWKde',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => 'aIT7pK9bVsnISaBx7EE6CfEBDaFo4dPFqDwoQZMg2aKjvojuTVY7xAp8I8ef',
                'email_verified_at' => '2024-05-15 16:46:33',
                'password_changed_at' => '2024-09-12 23:20:53',
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2024-09-02 18:54:37',
                'updated_at' => '2024-09-12 23:20:53',
            ),
            6 => 
            array (
                'id' => 7,
                'username' => 'ses',
                'email' => 'suganobshadam@gmail.com',
                'password' => '$2y$12$hikpLukTSmF4TBwFzZ7bVeCkn5uS64IuLywkv11eiCHEb7KTJEHhy',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => 'HLOP9qG1CFBNCVvvRIWuC14qWbi9L5J1RNodVJjgi7QdismGGMutuH9fvgLK',
                'email_verified_at' => '2024-05-15 16:46:33',
                'password_changed_at' => '2024-11-08 17:05:35',
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2024-09-02 19:24:53',
                'updated_at' => '2024-11-08 17:05:35',
            ),
            7 => 
            array (
                'id' => 8,
                'username' => 'janice.ong',
                'email' => 'janice.ong@ro9.dost.gov.ph',
                'password' => '$2y$12$lCqnedCshxaDrTF4crHrWOFFlth9PvLiHsPAbxFmJuDTk93TPPyze',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => 'RLr1VW91HeDLfmRPo1c4bIHXpunJ2q9eNZmGvv8EXRtcLMBuLc4ZbgoSyejR',
                'email_verified_at' => '2024-09-09 21:38:24',
                'password_changed_at' => '2024-09-09 21:45:32',
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2024-09-09 21:33:21',
                'updated_at' => '2024-10-02 05:01:39',
            ),
            8 => 
            array (
                'id' => 9,
                'username' => 'emapendergat',
                'email' => 'emapendergat95@gmail.com',
                'password' => '$2y$12$1vxW9H44hyimF05yOWu/yOq4HtyMbRCz.soujnAGEkkGFTdp7G6S.',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => 'P6yXUgpFyUPRF8Hz4100nNsKqagKNppel6BGJC8jMFLsiuIlb17Kzmlc9bjb',
                'email_verified_at' => '2024-09-09 23:51:52',
                'password_changed_at' => '2024-09-10 00:01:00',
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2024-09-09 23:51:20',
                'updated_at' => '2024-09-10 00:01:00',
            ),
            9 => 
            array (
                'id' => 10,
                'username' => 'Angelica',
                'email' => 'angelicajoytubo@gmail.com',
                'password' => '$2y$12$eSF2uOsIvHsmOOxGsuWuOeubIL5C/dg1.p3h8l0HnWxtIvIVCi/0O',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => 'lcADRX8ObUTtVj9iNikrgDBusfamoUMzVHx4qgzqxZzu34geWKMhwF0W00Yu',
                'email_verified_at' => '2024-09-10 17:16:42',
                'password_changed_at' => '2025-02-27 23:36:53',
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2024-09-10 17:12:58',
                'updated_at' => '2025-02-27 23:36:53',
            ),
            10 => 
            array (
                'id' => 11,
                'username' => 'rml',
                'email' => 'rubenjr1005@gmail.com',
                'password' => '$2y$12$SxUB6pTQvJFuzSeQaZaxA.oeFLRaHEdEwdCVU0j4xQmfK4PW0s3Ja',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => '9tem0aj0UMBDnThvPc7foT1TI04sfAE1ABbwwFbunxD6I1q3IUpzQGU8Ka4G',
                'email_verified_at' => '2024-09-10 21:46:57',
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2024-09-10 21:46:32',
                'updated_at' => '2024-09-17 20:02:28',
            ),
            11 => 
            array (
                'id' => 12,
                'username' => 'mac0905',
                'email' => 'miggyatilano@gmail.com',
                'password' => '$2y$12$0V2f8CpgebMOghTIN.hkXuheSr/QIQ34OJDSqaQDGMjyj7Lm6zaf.',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => 'zFdocWqscrXD75QfKndV84SPXXHNC7LhbJLbW9jL4ygriubqUBzLLoZckFGf',
                'email_verified_at' => '2024-09-10 22:32:31',
                'password_changed_at' => '2024-09-10 22:33:16',
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2024-09-10 22:32:08',
                'updated_at' => '2024-09-12 18:08:05',
            ),
            12 => 
            array (
                'id' => 13,
                'username' => 'mekkrr',
                'email' => 'kevinkarlramosramiso@gmail.com',
                'password' => '$2y$12$Op.oOb2gzh3VBeJQHSl/XuWB0mPGk9M.bTwnubly1oF3.RcJnua8i',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => '2024-09-11 16:55:14',
                'password_changed_at' => '2024-09-11 16:57:47',
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2024-09-11 16:54:39',
                'updated_at' => '2024-09-11 16:57:47',
            ),
            13 => 
            array (
                'id' => 14,
                'username' => 'analynsajiin',
                'email' => 'analynsajiin.dost9@gmail.com',
                'password' => '$2y$12$VJGLQG/BiTjaafMAkWrxA.zCvDOFjK5X7XfMThkwhnWxUu/mh8w7i',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => '3aaeOiss60vA5MBcHx0TExgfC95bl1Pb1ZPByfiO3o7vWhahhh2P7m4xlHga',
                'email_verified_at' => '2024-09-11 17:39:36',
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2024-09-11 17:10:03',
                'updated_at' => '2024-10-30 19:26:32',
            ),
            14 => 
            array (
                'id' => 15,
                'username' => 'rsg',
                'email' => 'rmgansan@gmail.com',
                'password' => '$2y$12$vBjBmfXUml7u8b8T4qKbkO0m/MJ4wxYM7t5SqEf1K/n7JUD/l.SYO',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => 'Be9Zgb969dXIR0jIgCmF6wUaPiDVlYUcQoJMZRh6ESa6sHcAqGj3DUScCzzG',
                'email_verified_at' => '2024-09-11 17:31:58',
                'password_changed_at' => '2024-09-11 17:34:28',
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2024-09-11 17:31:24',
                'updated_at' => '2024-09-11 17:34:28',
            ),
            15 => 
            array (
                'id' => 16,
                'username' => 'Ash',
                'email' => 'arleneherbieto@gmail.com',
                'password' => '$2y$12$viSEjAm5Z8BkSDJQ8eCQv.CpanGG8iXBrdIKw0iO87UFP6w3cQnbG',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => '63ecdHwfJVgxwLhDTOpySQ1tdCToEPVzPG3ujTdwGFefjNFcz1BOzXrRSAft',
                'email_verified_at' => '2024-09-17 21:31:33',
                'password_changed_at' => '2024-09-17 21:38:46',
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2024-09-12 16:37:38',
                'updated_at' => '2024-09-17 21:38:46',
            ),
            16 => 
            array (
                'id' => 17,
                'username' => 'rcj',
                'email' => 'jruishnova@gmail.com',
                'password' => '$2y$12$kWMfLCQy83dz3OQ8PSc6M.tMAqo9MwpXQeUyFgEMMYqJSTdYX3/t.',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => 's0PsBOfGNh8SSvLf3HHqFB3Qa0hfBvvacM3gxcH2WP5rBzUYQmvjMwvUBSJh',
                'email_verified_at' => '2024-09-13 18:48:42',
                'password_changed_at' => '2024-09-13 18:51:15',
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2024-09-13 18:47:26',
                'updated_at' => '2024-09-13 18:51:15',
            ),
            17 => 
            array (
                'id' => 18,
                'username' => 'ACF',
                'email' => 'franciscoannamae18@gmail.com',
                'password' => '$2y$12$1g/IaMlifaaNEMiIQcMz4um5bXLQ.mBDJfn/Mj2RWQxBZ5qm773Yy',
                'role' => 'Staff',
                'is_active' => 0,
                'is_new' => 1,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2024-09-13 19:05:15',
                'updated_at' => '2024-09-13 19:05:15',
            ),
            18 => 
            array (
                'id' => 19,
                'username' => 'EAV',
                'email' => 'evamaevilla@gmail.com',
                'password' => '$2y$12$//UdUPLBzCv.kxQzRU9tp.eLb6uJcg7hsHt/fkd4TTZsuFgCxbCRS',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => '2024-09-13 23:18:03',
                'password_changed_at' => '2024-09-13 23:20:03',
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2024-09-13 23:17:02',
                'updated_at' => '2024-09-13 23:20:03',
            ),
            19 => 
            array (
                'id' => 20,
                'username' => 'noel',
                'email' => 'protein63nt@gmail.com',
                'password' => '$2y$12$hsy4HImQ99Ci/in8m7ToB./lAfRybU3EQlEzYYRa8xEa7Qxcmn.RC',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => 'a5hmfzjFuR0CdB4r26ypJu5GbPkovuyGpza8amChf5CZLn20dfJCHOqicCFs',
                'email_verified_at' => '2024-05-15 16:46:33',
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2024-09-17 19:54:59',
                'updated_at' => '2024-09-17 21:07:28',
            ),
            20 => 
            array (
                'id' => 21,
                'username' => 'GIAN CARLO',
                'email' => 'giancarloacejas@gmail.com',
                'password' => '$2y$12$fIU/emeUUhwjve7P5W2aY.LX4jwSEckRO1IuObtjPLiTKJLPHcR1a',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => '2024-09-19 20:54:29',
                'password_changed_at' => '2024-09-19 21:02:34',
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2024-09-19 20:52:32',
                'updated_at' => '2024-09-19 21:02:34',
            ),
            21 => 
            array (
                'id' => 22,
                'username' => 'test',
                'email' => 'testnikrad@gmail.com',
                'password' => '$2y$12$F0vN04DkzddifrsJcR9NvuF7u5kXDsCgIhbAk1wk7wH/xl2ppMYH.',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => '2024-05-15 16:46:33',
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2024-12-03 18:23:25',
                'updated_at' => '2024-12-03 18:23:31',
            ),
            22 => 
            array (
                'id' => 23,
                'username' => 'zairil122911',
                'email' => 'zairil122911@gmail.com',
                'password' => '$2y$12$UBYqM/1IOAa5GB1VGQtQcOMceUOSl86Ns0A4xBA0OevA50WFO5iRO',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => '2024-05-15 16:46:33',
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2024-12-06 18:55:31',
                'updated_at' => '2024-12-06 18:55:37',
            ),
            23 => 
            array (
                'id' => 24,
                'username' => 'ong',
                'email' => 'oniangelongomez@gmail.com',
                'password' => '$2y$12$yuqe4jWKS9BygOxunJzC3ui2lk08aY1i/uC6PolgOkTWEib3laol6',
                'role' => 'Staff',
                'is_active' => 1,
                'is_new' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => '2024-05-15 16:46:33',
                'password_changed_at' => '2025-03-27 17:11:49',
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-02-06 22:58:53',
                'updated_at' => '2025-03-27 17:11:49',
            ),
        ));

        
    }
}